diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "left_wheel_joint"
  right_wheel: "right_wheel_joint"
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  cmd_vel_timeout: 5.0
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
  wheel_separation: 0.34
  wheel_radius: 0.1
  publish_cmd: true
  publish_wheel_joint_controller_state: true
  left_wheel_pid: {p: 100.0, i: 0.01, d: 1.0}
  right_wheel_pid: {p: 100.0, i: 0.01, d: 1.0}

# PID gains for gazebo_ros_control
gazebo_ros_control:
  pid_gains:
    left_wheel_joint:
      p: 100.0
      i: 0.01
      d: 1.0
    right_wheel_joint:
      p: 100.0
      i: 0.01
      d: 1.0